services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    volumes:
      - C:\Temp\seq-data:/data
    environment:
      ACCEPT_EULA: Y 
    restart: unless-stopped
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
